### ISSUE TITLE
找不到这篇论文 Deliberated Domain Bridging for Domain Adaptive Semantic Segmentation

### ISSUE THREAD

**Issue by yuheyuan** [xiaoachen98/DDB#1]
这个项目里面的
Arixv 链接404了。。。。

**Comment by xiaoachen98** [comment]
> 这个项目里面的 Arixv 链接404了。。。。

The arxiv paper will be public in tomorrow.

**Comment by xiaoachen98** [comment]
> 这个项目里面的 Arixv 链接404了。。。。

The arxiv paper will be public tomorrow.

**Comment by xiaoachen98** [comment]
> 这个项目里面的 Arixv 链接404了。。。。

Hi, the arxiv paper is public now.
