### ISSUE TITLE
where do the weight of student model comes from?

### ISSUE THREAD

**Issue by firekeepers** [xiaoachen98/DDB#10]
Thanks for your excellent job.I wonder how to initialize the student model in CKD stage.
In this paper , during CKD stage,the model trained by CRP and FCP will act as the ensemble teacher to teach student. I wonder how to initialize the student model .Does student initialize actually the same as one of CRP or FCP? 
Thanks!

**Comment by xiaoachen98** [comment]
Thanks for your interest! In the CKD step, the student model is initialized randomly just as same as CRP and FCP.

> Thanks for your excellent job.I wonder how to initialize the student model in CKD stage. In this paper , during CKD stage,the model trained by CRP and FCP will act as the ensemble teacher to teach student. I wonder how to initialize the student model .Does student initialize actually the same as one of CRP or FCP? Thanks!

**Comment by xiaoachen98** [comment]
> Thanks for your excellent job.I wonder how to initialize the student model in CKD stage. In this paper , during CKD stage,the model trained by CRP and FCP will act as the ensemble teacher to teach student. I wonder how to initialize the student model .Does student initialize actually the same as one of CRP or FCP? Thanks!

Thanks for your interest! In the CKD step, the student model is initialized randomly just as same as CRP and FCP.

**Comment by firekeepers** [comment]
> > Thanks for your excellent job.I wonder how to initialize the student model in CKD stage. In this paper , during CKD stage,the model trained by CRP and FCP will act as the ensemble teacher to teach student. I wonder how to initialize the student model .Does student initialize actually the same as one of CRP or FCP? Thanks!
> 
> Thanks for your interest! In the CKD step, the student model is initialized randomly just as same as CRP and FCP.

您好！我不确定是不是表述问题，想再确认一下，是否是这样：CKD阶段，学生模型在伊始是权重随机初始化的一个随机模型，CRP和FCP是由上一个阶段训练得到，通过checkpoint载入，然后用于获得一个更好的伪标签来训练学生模型，学生模型的精度由0增长到一个极高值。
是这样吗？还是说学生模型在CKD阶段的初始权重是CRP或者FCP得到的模型权重之一，其精度在原基础上获得一定提升？（例如58.2—>61.2）
非常感谢您的答复，谢谢！

**Comment by xiaoachen98** [comment]
> 

是的，CKD的学生模型是随机初始化然后精度从0开始的

**Comment by xiaoachen98** [comment]
> > > Thanks for your excellent job.I wonder how to initialize the student model in CKD stage. In this paper , during CKD stage,the model trained by CRP and FCP will act as the ensemble teacher to teach student. I wonder how to initialize the student model .Does student initialize actually the same as one of CRP or FCP? Thanks!
> > 
> > 
> > Thanks for your interest! In the CKD step, the student model is initialized randomly just as same as CRP and FCP.
> 
> 您好！我不确定是不是表述问题，想再确认一下，是否是这样：CKD阶段，学生模型在伊始是权重随机初始化的一个随机模型，CRP和FCP是由上一个阶段训练得到，通过checkpoint载入，然后用于获得一个更好的伪标签来训练学生模型，学生模型的精度由0增长到一个极高值。 是这样吗？还是说学生模型在CKD阶段的初始权重是CRP或者FCP得到的模型权重之一，其精度在原基础上获得一定提升？（例如58.2—>61.2） 非常感谢您的答复，谢谢！

是的，CKD的学生模型是随机初始化然后精度从0开始的

**Comment by firekeepers** [comment]
![图片](https://user-images.githubusercontent.com/40134009/211844047-b366f9ad-1fcd-45c4-ae66-cb64cffce580.png)

**Comment by firekeepers** [comment]
![图片](https://user-images.githubusercontent.com/40134009/211844139-5c532c80-25ba-4759-b7bc-07385c1b25d4.png)
您好，我注意到您在完成第一次学生模型的更新后，使用更新好的学生模型对MC和MF分别进行了更新，并且在伪代码中的表示是：MC^(r+1)=MS，MF^(r+1)=MS，是否可以理解成两个模型都等于更新后的学生模型？
