### ISSUE TITLE
Something about Table 1

### ISSUE THREAD

**Issue by wanderHZ** [xiaoachen98/DDB#3]
Dear Author，can you tell me whether deeplab or transformer is used for the experimental results in Table 1 of the paper?

**Comment by xiaoachen98** [comment]
> Dear Author，can you tell me whether deeplab or transformer is used for the experimental results in Table 1 of the paper?

All experiments in our paper are based on ResNet101 and DeepLabV2.

**Comment by wanderHZ** [comment]
Thank you for your prompt reply. And I have two more questions to ask.

In Table 1(b), the performance of 54.3 is achieved by using pseudo labels and classmix, but why does class path reach 58.2 in Table 5?

In addition, why is the result of Table 1(b) better than that of DACS(52.1)?

I'm a novice at UDA，thank you so much for your answer！

**Comment by xiaoachen98** [comment]
> Thank you for your prompt reply. And I have two more questions to ask.
> 
> In Table 1(b), the performance of 54.3 is achieved by using pseudo labels and classmix, but why does class path reach 58.2 in Table 5?
> 
> In addition, why is the result of Table 1(b) better than that of DACS(52.1)?
> 
> I'm a novice at UDA，thank you so much for your answer！

Thanks for your attention! The performance gain is because of the batchsize and we have pointed this out in the implementation details. We use batchsize=2 in Table 1 for repetitive and comprehensive experiments and batchsize=4 in the final experiments for a fair comparison with other SOTA methods.
