### ISSUE TITLE
how many GPUS used.

### ISSUE THREAD

**Issue by yuheyuan** [xiaoachen98/DDB#4]
I only have two 3090 GPUs. In your parer, you said you use 3090 GPUs.
In proDA, they need 4 GPU. I find I can't reproduce their performance because CUDA Memory limit.
So I want to know if your code need those GPUS

**Comment by xiaoachen98** [comment]
> 

Following the readme file, you can choose to use 1 or 2 GPUs to train your own model with different commands.
