### ISSUE TITLE
Missing module dass.datasets.uda_dataset

### ISSUE THREAD

**Issue by yuheyuan** [xiaoachen98/DDB#5]
```txt
(yy_ddb) ailab@ailab:/media/ailab/data/yy/DDB$ python tools/test.py test_cityscapes.py yy_weights/weight.pth --eval mIoU
Traceback (most recent call last):
  File "tools/test.py", line 21, in <module>
    import dass  # register custom modules
  File "/media/ailab/data/yy/DDB/dass/__init__.py", line 2, in <module>
    from .datasets import *
  File "/media/ailab/data/yy/DDB/dass/datasets/__init__.py", line 2, in <module>
    from .uda_dataset import UDADataset
ModuleNotFoundError: No module named 'dass.datasets.uda_dataset'
```
There is no uda_dataset in dir DDB/dass/datasets/

**Comment by xiaoachen98** [comment]
> ```
> (yy_ddb) ailab@ailab:/media/ailab/data/yy/DDB$ python tools/test.py test_cityscapes.py yy_weights/weight.pth --eval mIoU
> Traceback (most recent call last):
>   File "tools/test.py", line 21, in <module>
>     import dass  # register custom modules
>   File "/media/ailab/data/yy/DDB/dass/__init__.py", line 2, in <module>
>     from .datasets import *
>   File "/media/ailab/data/yy/DDB/dass/datasets/__init__.py", line 2, in <module>
>     from .uda_dataset import UDADataset
> ModuleNotFoundError: No module named 'dass.datasets.uda_dataset'
> ```
> 
> There is no uda_dataset in dir DDB/dass/datasets/

Sorry for the bugs. And we have already fixed it.
