### ISSUE TITLE
I need to apply for access to the Google drive you provided

### ISSUE THREAD

**Issue by TianX1nYu** [xiaoachen98/DDB#9]
Hello, I can't access your Google drive, can you cancel the permission setting, or apply through my access

**Comment by xiaoachen98** [comment]
> Hello, I can't access your Google drive, can you cancel the permission setting, or apply through my access

Sorry, we don't meet this problem. You can send me your google email and I will add your account to the google drive group.

**Comment by TianX1nYu** [comment]
I replied to your email once before, but you may not have received it. I still cannot access the link of "weight", so I reply you again here, my Google email is: tianxinyu07@gmail.com. 
Sorry to bother you again, thank you very much.

**Comment by xiaoachen98** [comment]
> I replied to your email once before, but you may not have received it. I still cannot access the link of "weight", so I reply you again here, my Google email is: [tianxinyu07@gmail.com](mailto:tianxinyu07@gmail.com). Sorry to bother you again, thank you very much.

You can click the BaiduYun (https://pan.baidu.com/s/1XIvYP9xl76RzgcyxO49Nyg?pwd=c2i3) link to download weight files now.

**Comment by TianX1nYu** [comment]
Hello, I have a question for you. The scores of the two teacher networks trained by stage1 DPDB reported in your article are 56.5 and 58.2 respectively in table 5 or table 8, but when I reproduce them based on the code you provided, I get 54.14 and 57.18 respectively. . Does the config file you provided match exactly what you report?
Through the code, it is found that your configuration file does not use the sample selection strategy in DAFormer. Is the score of 56.5 and 58.2 due to the use of the sample selection strategy of DAFormer?

**Comment by xiaoachen98** [comment]
> Hello, I have a question for you. The scores of the two teacher networks trained by stage1 DPDB reported in your article are 56.5 and 58.2 respectively in table 5 or table 8, but when I reproduce them based on the code you provided, I get 54.14 and 57.18 respectively. . Does the config file you provided match exactly what you report? Through the code, it is found that your configuration file does not use the sample selection strategy in DAFormer. Is the score of 56.5 and 58.2 due to the use of the sample selection strategy of DAFormer?

We did not use the sampling strategy and the existence of the sampling code is because this repo is based on DAFormer's codebase. We ran 3 times of experiments and report the medium results.
